// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2837a2920481fb5c39d6efa11ef40657fd670d13/nodemailer-stub-transport/nodemailer-stub-transport.d.ts
declare module "nodemailer-stub-transport" {
    import * as nodemailer from "nodemailer";

    namespace StubTransportStatic {
        /**
         * Options.
         * @interface
         */
        export interface Options {
            /**
             * Specifies a custom error.
             * @type {any}
             */
            error?: any;

            /**
             * Value that indicates if the BCC addresses must be included in generated message.
             * @type {boolean}
             */
            keepBcc?: boolean;
        }
    }

    /**
     * Creates a stub transport.
     * @param {Options} [options] Options.
     * @return {Transport} The stub transport.
     */
    function stubTransport(options?: StubTransportStatic.Options): nodemailer.Transport;
    export = stubTransport;
}
