module.exports = {
    "Message": "OK",
        "Code": 0,
            "Data": [
                {
                    "ProductId": "UTLAIRTIMEUG",
                    "ReferenceSchema": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"MSISDN\":{\"type\":\"string\"}},\"required\":[\"MSISDN\"]}",
                    "Name": "UTL Airtime",
                    "ShortDescription": "UTL Airtime Service",
                    "LongDescription": "UTL Airtime Service. Buy Uganda Telecom Airtime",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/utl.jpg",
                    "ThumbnailUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/utl.jpg",
                    "Website": "http://www.utl.co.ug/",
                    "ProductItems": null
                },
                {
                    "ProductId": "AFRICELLDATABUNDLESUG",
                    "ReferenceSchema": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"MSISDN\":{\"type\":\"string\"},\"BundleCode\":{\"type\":\"string\"}},\"required\":[\"MSISDN\",\"BundleCode\"]}",
                    "Name": "Africell Data Bundles",
                    "ShortDescription": "Africell Data Bundles Service",
                    "LongDescription": "Africell Data Bundles Service. Buy Africell Data Bundles",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/Africell-Data-Packages.jpg",
                    "ThumbnailUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/Africell-Data-Packages.jpg",
                    "Website": "http://africell.ug/",
                    "ProductItems": null
                },
                {
                    "ProductId": "PAYMENT",
                    "ReferenceSchema": null,
                    "Name": "No Product",
                    "ShortDescription": "No Product",
                    "LongDescription": "No Product",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "https://intelworldsstorage.blob.core.windows.net/tiketi/images/tiketi-merchants/(GIF%20Image,%20400%C2%A0%C3%97%C2%A0300%20pixels).gif",
                    "ThumbnailUri": "https://intelworldsstorage.blob.core.windows.net/tiketi/images/tiketi-merchants/(GIF%20Image,%20400%C2%A0%C3%97%C2%A0300%20pixels).gif",
                    "Website": "http://www.example.com",
                    "ProductItems": null
                },
                {
                    "ProductId": "VODAFONEDATABUNDLESUG",
                    "ReferenceSchema": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"Recipient\":{\"type\":\"string\"},\"BundleCode\":{\"type\":\"integer\"}},\"required\":[\"Recipient\",\"BundleCode\"]}",
                    "Name": "Vodafone Uganda Internet Data Bundles",
                    "ShortDescription": "Vodafone Uganda Internet Data Bundles Service",
                    "LongDescription": "Vodafone Uganda Internet Data Bundles Service",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/vodafone.png",
                    "ThumbnailUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/vodafone.png",
                    "Website": "http://www.vodafone.co.ug",
                    "ProductItems": null
                },
                {
                    "ProductId": "VODAFONEAIRTIMEUG",
                    "ReferenceSchema": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"Recipient\":{\"type\":\"string\"}},\"required\":[\"Recipient\"]}",
                    "Name": "Vodafone Uganda Airtime",
                    "ShortDescription": "Vodafone Uganda Airtime Service",
                    "LongDescription": "Vodafone Uganda Service. Buy Vodafone Uganda Airtime",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/vodafone.png",
                    "ThumbnailUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/vodafone.png",
                    "Website": "http://www.vodafone.co.ug",
                    "ProductItems": null
                },
                {
                    "ProductId": "AFRICELLAIRTIMEUG",
                    "ReferenceSchema": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"MSISDN\":{\"type\":\"string\"}},\"required\":[\"MSISDN\"]}",
                    "Name": "Africell Airtime",
                    "ShortDescription": "Africell Airtime Service",
                    "LongDescription": "Africell Airtime Service. Buy Africell Airtime",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/africell.jpeg",
                    "ThumbnailUri": "https://intelworldsstorage.blob.core.windows.net/intelipay/images/africell.jpeg",
                    "Website": "http://example.com",
                    "ProductItems": null
                },
                {
                    "ProductId": "TESTPRODCTUG",
                    "ReferenceSchema": null,
                    "Name": "Airtel Airtime",
                    "ShortDescription": "Earn money by selling airtel airtime",
                    "LongDescription": "Earn money by selling airtel airtime",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "http://intelworldsstorage.blob.core.windows.net/intelipay/airtel.png",
                    "ThumbnailUri": "http://intelworldsstorage.blob.core.windows.net/intelipay/airtel.png",
                    "Website": "http://africa.airtel.com/wps/wcm/connect/africarevamp/Uganda/",
                    "ProductItems": null
                },
                {
                    "ProductId": "IP2WALLETTOPUPUG",
                    "ReferenceSchema": null,
                    "Name": "IP2 Wallet Topup",
                    "ShortDescription": "Wallet Topup",
                    "LongDescription": "IP2 Wallet Topup",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "http://ec2-54-148-117-189.us-west-2.compute.amazonaws.com/Content/img/logo-light.png",
                    "ThumbnailUri": "http://ec2-54-148-117-189.us-west-2.compute.amazonaws.com/Content/img/logo-light.png",
                    "Website": "http://example.com",
                    "ProductItems": null
                },
                {
                    "ProductId": "TIKETI",
                    "ReferenceSchema": null,
                    "Name": "Tiketi",
                    "ShortDescription": "Tiketi",
                    "LongDescription": "Tiketi",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "http://carinacustomer.azurewebsites.net/Images/logo2.png",
                    "ThumbnailUri": "http://carinacustomer.azurewebsites.net/Images/logo2.png",
                    "Website": "http://carinacustomer.azurewebsites.net",
                    "ProductItems": null
                },
                {
                    "ProductId": "AIRTELBUNDLESUG",
                    "ReferenceSchema": null,
                    "Name": "Airtel Data Bundles",
                    "ShortDescription": "Airtel Data Bundles",
                    "LongDescription": "Airtel Internet Data Bundles",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "http://intelworldsstorage.blob.core.windows.net/intelipay/airtel.png",
                    "ThumbnailUri": "http://intelworldsstorage.blob.core.windows.net/intelipay/airtel.png",
                    "Website": "http://example.com",
                    "ProductItems": null
                },
                {
                    "ProductId": "LIVETICKETUG",
                    "ReferenceSchema": null,
                    "Name": "Live Ticket",
                    "ShortDescription": "Tap and Go",
                    "LongDescription": "Live Ticket. Tap and Go",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "http://carinacustomer.azurewebsites.net/Images/logo2.png",
                    "ThumbnailUri": "http://carinacustomer.azurewebsites.net/Images/logo2.png",
                    "Website": "http://carinacustomer.azurewebsites.net",
                    "ProductItems": null
                },
                {
                    "ProductId": "MTNAIRTIMEUG",
                    "ReferenceSchema": null,
                    "Name": "MTN Airtime",
                    "ShortDescription": "MTN Airtime",
                    "LongDescription": "MTN Airtime Service.",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "https://intelworldsstorage.blob.core.windows.net/tiketi/images/tiketi-merchants/(JPEG%20Image,%20300%C2%A0%C3%97%C2%A0300%20pixels).jpg",
                    "ThumbnailUri": "https://intelworldsstorage.blob.core.windows.net/tiketi/images/tiketi-merchants/(JPEG%20Image,%20300%C2%A0%C3%97%C2%A0300%20pixels).jpg",
                    "Website": "http://mtn.co.ug/",
                    "ProductItems": null
                },
                {
                    "ProductId": "MTNBUNDLESUG",
                    "ReferenceSchema": "{\"$schema\":\"http://json-schema.org/draft-04/schema#\",\"type\":\"object\",\"properties\":{\"BundleCode\":{\"type\":\"string\"},\"MSISDN\":{\"type\":\"string\"},\"Amount\":{\"type\":\"integer\"}},\"required\":[\"BundleCode\",\"MSISDN\",\"Amount\"]}",
                    "Name": "MTN Data Bundles",
                    "ShortDescription": "MTN Internet Bundles",
                    "LongDescription": "MTN Data/Internet Bundles Service.",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "https://intelworldsstorage.blob.core.windows.net/tiketi/images/tiketi-merchants/(JPEG%20Image,%20300%C2%A0%C3%97%C2%A0300%20pixels).jpg",
                    "ThumbnailUri": "https://intelworldsstorage.blob.core.windows.net/tiketi/images/tiketi-merchants/(JPEG%20Image,%20300%C2%A0%C3%97%C2%A0300%20pixels).jpg",
                    "Website": "http://www.mtn.co.ug",
                    "ProductItems": null
                },
                {
                    "ProductId": "AIRTELAIRTIMEUG",
                    "ReferenceSchema": null,
                    "Name": "Airtel Airtime",
                    "ShortDescription": "Earn money by selling airtel airtime",
                    "LongDescription": "Earn money by selling airtel airtime",
                    "CurrencyCode": "UGX",
                    "CountryCode": "256",
                    "ImageUri": "http://intelworldsstorage.blob.core.windows.net/intelipay/airtel.png",
                    "ThumbnailUri": "http://intelworldsstorage.blob.core.windows.net/intelipay/airtel.png",
                    "Website": "http://africa.airtel.com/wps/wcm/connect/africarevamp/Uganda/",
                    "ProductItems": null
                }
            ],
                "CorrelationId": null
}